language: node_js
node_js:
  - "4.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# install terraform
before_deploy:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.8.7/terraform_0.8.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - export PATH=$PATH:$(pwd)/infra
  - rm -f terraform.zip

# terraform apply
deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"